CREATE ROLE candlepin WITH LOGIN ENCRYPTED PASSWORD 'candlepin' CREATEDB;
CREATE DATABASE candlepin WITH OWNER candlepin TEMPLATE template0 ENCODING 'UTF8';
GRANT ALL PRIVILEGES ON DATABASE candlepin TO candlepin;
GRANT ALL PRIVILEGES ON DATABASE postgres TO candlepin;
ALTER ROLE candlepin WITH superuser;
